// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aydusqwtznvohjxhgkby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5ZHVzcXd0em52b2hqeGhna2J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5ODI5OTgsImV4cCI6MjA2MjU1ODk5OH0.FtVgBKFD8BE2R97_l7LCk64vwTZGuh_8ABH9y0SQEQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);